### ISSUE TITLE
VBlood Boss Start

### ISSUE THREAD

**Issue by BusterGuts78** [oscarpedrero/Notify#3]
No issue and Thank you for the mod.

Curious if there is any chance of having an announcement of when someone fights a VBlood Boss?

I currently rent a server with mods and it'd be cool to know when players are fighting bosses.  Then we'd be able to offer and help or just leave them alone.  Maybe an admin command, who knows.

Currently run a PVE server and it'd be neat to have a mod that would allow pvp at the colosseum.

**Comment by oscarpedrero** [comment]
Sorry for taking so long to respond, but I had missed this suggestion.

I'm saving this feature for a future update, now I'm updating all mods to Gloomrot.

**Comment by oscarpedrero** [comment]
@BusterGuts78  Sorry for taking so long to respond, but I had missed this suggestion.

I'm saving this feature for a future update, now I'm updating all mods to Gloomrot.

**Comment by oscarpedrero** [comment]
Sorry for taking so long to respond, but I had missed this suggestion.

I'm saving this feature for a future update, now I'm updating all mods to Gloomrot.
