### ISSUE TITLE
VRising 1.0 Update

### ISSUE THREAD

**Issue by jgentil** [oscarpedrero/Notify#6]
Are there plans to update this for the 1.0 update?  I realize it's early and only prerelease versions of BepinEx are available at the time of this writing, but I wanted to check.  There's definitely interest in this being continued.

Thanks!

**Comment by oscarpedrero** [comment]
Yes, I'm going to continue it, I haven't had time to get started yet ;)

**Comment by Lulumage** [comment]
im using it for my server but keep getting ignore message from some vbloods, and otheres get the announcement but also spam ignore T_T

**Comment by oscarpedrero** [comment]
Yes, it is a bug and it means that the VBloods list is not updated. I'll review it soon and upload a new version ;)

**Comment by oscarpedrero** [comment]
Fixed in the new version.
