### ISSUE TITLE
custom login message not working. ver. v3.0.5 with core v1.2.1

### ISSUE THREAD

**Issue by Djizox** [oscarpedrero/Notify#8]
it only shows the standart message "User is online". am i missing somthing?
is the config wrong or
![billede](https://github.com/oscarpedrero/BloodyNotify/assets/11280026/ae93a51f-fabf-4eec-9ea3-4c180e7f3391)

**Comment by oscarpedrero** [comment]
use `users_online.json` not `default_announce.json`

**Comment by Djizox** [comment]
As seen in the picture you can see it's the file I'm already editing. Upper left corner.

**Comment by oscarpedrero** [comment]
@Djizox You haven't understood me, you are using the wrong file...

## Customize Player Announce

To configure the customize messages per player connected, you only have to edit the configuration file that is in **/BepInEx/config/BloodyNotify/users_online.json**

```json
{
   "CharacterName": "#user# The best player of server is online!",
   "OtherCharacterName": "The most wanted #user# is online!"
}
```
> The text string #user# is used to overwrite the name of the corresponding player(s)

To configure the customize messages per player disconnected, you only have to edit the configuration file that is in **/BepInEx/config/BloodyNotify/users_offline.json**

```json
{
   "CharacterName": "#user# The best player of server is offline!",
   "OtherCharacterName": "The most wanted #user# is offline!"
}
```
> The text string #user# is used to overwrite the name of the corresponding player(s)

**Comment by oscarpedrero** [comment]
Sorry, I didn't see it... you're missing a comma at the end of each line, except for the last one, which shouldn't have one.
